language: go

go_import_path: github.com/digitalocean/digitalocean-cloud-controller-manager

go:
  - "1.11.x"
  - "1.12.x"

dist: trusty

script:
  - GO111MODULE=on go install -mod=vendor golang.org/x/lint/golint
  - make ci

notifications:
  email: false
